import { useCallback, useEffect, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { api } from '../lib/apiClient'

function ReasonModal({ title, onConfirm, onClose }) {
  const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function submit(event) { event.preventDefault(); if (!reason.trim()) return; setBusy(true); try { await onConfirm(reason.trim()); onClose() } catch (issue) { setError(issue.message) } finally { setBusy(false) } }
  return <div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-xl bg-white p-5 shadow-xl"><h2 className="text-lg font-semibold text-slate-800">{title}</h2><p className="mt-1 text-sm text-slate-600">A reason is required and will be added to the audit log.</p><textarea required value={reason} onChange={(event) => setReason(event.target.value)} className="mt-4 min-h-24 w-full rounded-lg border border-slate-300 p-3 text-sm outline-none focus:border-slate-600" placeholder="Reason for this action" />{error && <p className="mt-2 text-sm text-red-700">{error}</p>}<div className="mt-4 flex justify-end gap-3"><button type="button" onClick={onClose} className="text-sm text-slate-600 underline">Cancel</button><button disabled={busy || !reason.trim()} className="rounded-lg bg-slate-700 px-4 py-2 text-sm font-semibold text-white">{busy ? 'Saving…' : 'Confirm'}</button></div></form></div>
}
function Identity({ author }) { return <span className="flex items-center gap-2 text-sm"><span className="grid size-7 place-items-center overflow-hidden rounded-full bg-slate-200 text-xs font-bold text-slate-600">{author.avatar_url ? <img src={author.avatar_url} alt="" className="size-full object-cover" /> : author.full_name.slice(0, 1)}</span><span><b className="font-medium text-slate-800">{author.full_name}</b> <span className="text-slate-500">@{author.username}</span>{author.group_number > 0 && <span className="ml-2 text-slate-500">Group {author.group_number}{author.semester ? ` · Sem ${author.semester}` : ''}</span>}</span></span> }
function AdminComment({ comment, onDelete }) { return <li className="mt-3 list-none border-l border-slate-300 pl-3"><Identity author={comment.author} /><p className={`mt-1 text-sm ${comment.is_deleted ? 'italic text-slate-500' : 'text-slate-800'}`}>{comment.is_deleted ? 'Comment removed.' : comment.content}</p>{!comment.is_deleted && <button onClick={() => onDelete(comment.id)} className="mt-1 text-xs text-red-700 underline">Delete</button>}{comment.replies?.length > 0 && <ul className="m-0 p-0">{comment.replies.map((reply) => <AdminComment key={reply.id} comment={reply} onDelete={onDelete} />)}</ul>}</li> }

export function AdminFeed() {
  const [posts, setPosts] = useState([]); const [cursor, setCursor] = useState(null); const [includeDeleted, setIncludeDeleted] = useState(false); const [comments, setComments] = useState({}); const [modal, setModal] = useState(null); const [error, setError] = useState('')
  const load = useCallback(async (reset = true) => { try { const response = await api.get(`/admin/posts?includeDeleted=${includeDeleted}${!reset && cursor ? `&cursor=${encodeURIComponent(cursor)}` : ''}`); setPosts((current) => reset ? response.posts : [...current, ...response.posts]); setCursor(response.next_cursor); setError('') } catch (issue) { setError(issue.message) } }, [cursor, includeDeleted])
  useEffect(() => { void load(true) }, [includeDeleted])
  async function toggleComments(postId) { if (comments[postId]) return setComments((current) => ({ ...current, [postId]: null })); try { const response = await api.get(`/admin/comments?postId=${postId}`); setComments((current) => ({ ...current, [postId]: response.comments })) } catch (issue) { setError(issue.message) } }
  return <section><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold">Post moderation</h2><label className="text-sm text-slate-600"><input type="checkbox" checked={includeDeleted} onChange={(event) => setIncludeDeleted(event.target.checked)} /> Include removed</label></div>{error && <p className="mb-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{posts.map((post) => <article key={post.id} className={`border-b border-slate-200 py-5 ${post.is_deleted ? 'opacity-60' : ''}`}><div className="flex items-start justify-between gap-3"><Identity author={post.author} /><span className="font-mono text-xs text-slate-500">{new Date(post.created_at).toLocaleString()}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{post.is_deleted ? 'Post removed.' : post.content}</p>{(post.image_url_1 || post.image_url_2) && <div className="mt-3 grid max-w-sm grid-cols-2 gap-2">{[post.image_url_1, post.image_url_2].filter(Boolean).map((url) => <img key={url} src={url} alt="Post attachment" className="aspect-square rounded object-cover" />)}</div>}<div className="mt-3 flex gap-4 text-xs"><button onClick={() => void toggleComments(post.id)} className="text-slate-700 underline">{comments[post.id] ? 'Hide comments' : 'View comments'}</button>{!post.is_deleted && <button onClick={() => setModal({ type: 'post', id: post.id })} className="text-red-700 underline">Delete post</button>}</div>{comments[post.id] && <ul className="m-0 mt-3 p-0">{comments[post.id].map((comment) => <AdminComment key={comment.id} comment={comment} onDelete={(id) => setModal({ type: 'comment', id })} />)}</ul>}</article>)}{cursor && <button onClick={() => void load(false)} className="mt-5 rounded border border-slate-300 px-3 py-2 text-sm">Load more</button>}{modal && <ReasonModal title={`Delete ${modal.type}`} onClose={() => setModal(null)} onConfirm={async (reason) => { await api.delete(`/admin/${modal.type}s/${modal.id}`, { body: { reason } }); await load(true) }} />}</section>
}

export function AdminUsers() {
  const [query, setQuery] = useState(''); const [users, setUsers] = useState([]); const [modal, setModal] = useState(null); const [error, setError] = useState('')
  const load = useCallback(async () => { try { const response = await api.get(`/admin/users${query ? `?q=${encodeURIComponent(query)}` : ''}`); setUsers(response.users); setError('') } catch (issue) { setError(issue.message) } }, [query])
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer) }, [load])
  return <section><h2 className="text-xl font-semibold">Students</h2><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name or username" className="my-4 w-full max-w-md rounded border border-slate-300 px-3 py-2 text-sm" />{error && <p className="mb-3 text-sm text-red-700">{error}</p>}<div className="overflow-x-auto rounded border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-100 text-xs uppercase text-slate-500"><tr><th className="p-3">Student</th><th className="p-3">Group</th><th className="p-3">Semester</th><th className="p-3">Posts</th><th className="p-3">Comments</th><th className="p-3">Status</th><th className="p-3" /></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-t border-slate-200"><td className="p-3"><b>{user.full_name}</b><span className="ml-2 text-slate-500">@{user.username}</span></td><td className="p-3">{user.group_number || 'Unassigned'}</td><td className="p-3">{user.semester ?? '—'}</td><td className="p-3">{user.post_count}</td><td className="p-3">{user.comment_count}</td><td className="p-3">{user.is_banned ? 'Banned' : 'Active'}</td><td className="p-3 text-right"><button onClick={() => setModal({ id: user.id, banned: user.is_banned })} className={user.is_banned ? 'text-slate-700 underline' : 'text-red-700 underline'}>{user.is_banned ? 'Unban' : 'Ban'}</button></td></tr>)}</tbody></table></div>{modal && <ReasonModal title={modal.banned ? 'Unban user' : 'Ban user'} onClose={() => setModal(null)} onConfirm={async (reason) => { await api.patch(`/admin/users/${modal.id}/${modal.banned ? 'unban' : 'ban'}`, { reason }); await load() }} />}</section>
}

export function AdminModerationLog() {
  const [entries, setEntries] = useState([]); const [error, setError] = useState('')
  useEffect(() => { void api.get('/admin/moderation-log').then((response) => setEntries(response.entries)).catch((issue) => setError(issue.message)) }, [])
  return <section><h2 className="text-xl font-semibold">Moderation log</h2>{error && <p className="mt-4 text-sm text-red-700">{error}</p>}<div className="mt-4 overflow-x-auto rounded border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-100 text-xs uppercase text-slate-500"><tr><th className="p-3">Admin</th><th className="p-3">Action</th><th className="p-3">Target</th><th className="p-3">Reason</th><th className="p-3">When</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id} className="border-t border-slate-200"><td className="p-3">{entry.admin.full_name} <span className="text-slate-500">@{entry.admin.username}</span></td><td className="p-3">{entry.action}</td><td className="p-3 font-mono text-xs">{entry.target_type}:{entry.target_id.slice(0, 8)}</td><td className="p-3">{entry.reason || '—'}</td><td className="p-3 text-xs text-slate-500">{new Date(entry.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>
}

export default function AdminPage() {
  const location = useLocation(); const tab = location.pathname.includes('/users') ? 'users' : location.pathname.includes('/log') ? 'log' : 'feed'
  return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-800"><section className="mx-auto max-w-5xl"><header className="border-b border-slate-300 pb-5"><p className="font-mono text-xs uppercase tracking-wider text-slate-500">Elevated access</p><h1 className="mt-2 text-2xl font-semibold">Moderation dashboard</h1><nav className="mt-5 flex gap-4 text-sm"><Link className={tab === 'feed' ? 'font-semibold text-slate-900 underline' : 'text-slate-600'} to="/admin">Feed</Link><Link className={tab === 'users' ? 'font-semibold text-slate-900 underline' : 'text-slate-600'} to="/admin/users">Students</Link><Link className={tab === 'log' ? 'font-semibold text-slate-900 underline' : 'text-slate-600'} to="/admin/log">Audit log</Link><Link className="ml-auto text-slate-600 underline" to="/">Student view</Link></nav></header><div className="py-7">{tab === 'feed' ? <AdminFeed /> : tab === 'users' ? <AdminUsers /> : <AdminModerationLog />}</div></section></main>
}
