import { useState } from 'react'
import { Link } from 'react-router-dom'
import { AuthLayout } from '../components/AuthLayout'
import { PasswordInput } from '../components/PasswordInput'
import { supabase } from '../lib/supabase'

export default function SignupPage() {
  const [form, setForm] = useState({ fullName: '', username: '', email: '', password: '' }); const [error, setError] = useState(''); const [confirmationSent, setConfirmationSent] = useState(false); const [submitting, setSubmitting] = useState(false)
  const change = (field) => (event) => setForm({ ...form, [field]: event.target.value })
  async function submit(event) { event.preventDefault(); setError(''); setSubmitting(true); setConfirmationSent(false); const { data, error: signUpError } = await supabase.auth.signUp({ email: form.email.trim(), password: form.password, options: { data: { full_name: form.fullName.trim(), username: form.username.trim() }, emailRedirectTo: `${window.location.origin}/login?verified=1` } }); setSubmitting(false); if (signUpError) return setError(signUpError.message); if (data.session) { await supabase.auth.signOut(); return setError('Email verification is not enabled in Supabase yet. Turn on Confirm email in Authentication → Providers → Email, then sign up again.') } setConfirmationSent(true) }
  return <AuthLayout title="Join the bootcamp" subtitle="Create your account, then verify your email before your first login." footer={<>Already have an account? <Link className="font-medium text-[#137B45]" to="/login">Log in</Link></>}><form onSubmit={submit} className="space-y-4"><label>Full name<input required placeholder="John Doe" value={form.fullName} onChange={change('fullName')} /></label><label>Username<input required minLength="3" placeholder="john_doe" value={form.username} onChange={change('username')} /></label><label>Email<input required type="email" autoComplete="email" placeholder="you@example.com" value={form.email} onChange={change('email')} /></label><label>Password<PasswordInput value={form.password} onChange={change('password')} autoComplete="new-password" placeholder="Create a secure password" /></label>{error && <p role="alert" className="error">{error}</p>}{confirmationSent && <p className="success">Verification email sent. Open the link in your inbox, then return here to log in.</p>}<button className="primary-button w-full" disabled={submitting}>{submitting ? 'Creating account…' : 'Create account'}</button></form></AuthLayout>
}
