import { ImagePlus, Send } from 'lucide-react'
import { useRef, useState } from 'react'
import { api } from '../lib/apiClient'
import { supabase } from '../lib/supabase'

const MAX_CONTENT = 3000
function randomStoragePath(file) { const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '-').slice(-100) || 'image'; return `${crypto.randomUUID()}/${safeName}` }
async function uploadImage(file) { const { default: imageCompression } = await import('browser-image-compression'); const compressed = await imageCompression(file, { maxSizeMB: 0.9, maxWidthOrHeight: 1920, useWebWorker: true }); const path = randomStoragePath(compressed); const { error } = await supabase.storage.from('post-images').upload(path, compressed, { upsert: false, contentType: compressed.type || file.type }); if (error) throw error; return supabase.storage.from('post-images').getPublicUrl(path).data.publicUrl }

export function CreatePostForm({ onCreated }) {
  const fileInput = useRef(null); const [content, setContent] = useState(''); const [files, setFiles] = useState([]); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('')
  function chooseFiles(event) { const next = Array.from(event.target.files ?? []); if (next.length > 2 || next.some((file) => !file.type.startsWith('image/'))) { setError('Choose up to two image files.'); event.target.value = ''; return } setError(''); setFiles(next) }
  async function submit(event) { event.preventDefault(); if (!content.trim()) return; setError(''); setSubmitting(true); try { const urls = await Promise.all(files.map(uploadImage)); const post = await api.post('/posts', { content: content.trim(), image_url_1: urls[0], image_url_2: urls[1] }); setContent(''); setFiles([]); fileInput.current.value = ''; onCreated?.(post) } catch (uploadError) { setError(uploadError.message || 'Could not post your update.') } finally { setSubmitting(false) } }
  return <form onSubmit={submit} className="mt-6 rounded-2xl border border-[#D6E5D9] bg-white p-5 shadow-sm"><div className="flex gap-3"><AnonymousMark /><div className="min-w-0 flex-1"><div className="flex items-center justify-between"><p className="text-sm font-bold text-[#234033]">Your daily check-in</p><span className="rounded-full bg-[#EAF6ED] px-2.5 py-1 text-[11px] font-bold text-[#137B45]">Anonymous</span></div><textarea value={content} maxLength={MAX_CONTENT} required placeholder="What did you study, solve, or understand today?" onChange={(event) => setContent(event.target.value)} className="mt-3 min-h-30 w-full resize-y rounded-xl border border-[#D6E5D9] bg-[#FCFDFC] p-3 text-sm leading-6 outline-none focus:border-[#16834A] focus:ring-4 focus:ring-[#DDF2E4]" /><div className="mt-2 flex items-center justify-between gap-3 text-xs text-[#718277]"><span>{files.length ? `${files.length} image${files.length > 1 ? 's' : ''} ready` : 'Up to 2 images'}</span><span className={content.length > 2700 ? 'text-[#B77A1B]' : ''}>{content.length}/{MAX_CONTENT}</span></div>{error && <p role="alert" className="error mt-3">{error}</p>}<div className="mt-4 flex items-center justify-between gap-3"><label className="inline-flex cursor-pointer items-center gap-2 text-sm font-bold text-[#137B45]"><ImagePlus size={18} /> Add images<input ref={fileInput} className="sr-only" type="file" accept="image/*" multiple onChange={chooseFiles} /></label><button className="primary-button inline-flex items-center gap-2" disabled={submitting || !content.trim()}>{submitting ? 'Posting…' : <>Post check-in <Send size={16} /></>}</button></div></div></div></form>
}

export function AnonymousMark() { return <span aria-hidden="true" className="grid size-10 shrink-0 place-items-center rounded-full bg-[#EAF6ED] text-[#137B45]"><svg viewBox="0 0 24 24" className="size-5 fill-none stroke-current" strokeWidth="1.8"><path d="M19.5 3.5C12 4 6 8.5 6 15a5.5 5.5 0 0 0 5.5 5.5c6.5 0 9.5-6 8-17Z" /><path d="M4 20c3.5-4.5 7-7.25 12-10" /></svg></span> }
