import { Heart, MessageCircle, RefreshCw } from 'lucide-react'
import { useCallback, useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../lib/apiClient'
import { useRealtimeEvent } from '../realtime/RealtimeContext'
import { AnonymousMark } from './CreatePostForm'

function PostCard({ post, onChange, onDelete }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const date = new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(post.created_at))
  async function toggleLike() { setBusy(true); setError(''); try { if (post.liked_by_me) await api.delete(`/likes/post/${post.id}`); else await api.post('/likes', { target_type: 'post', target_id: post.id }); onChange({ ...post, liked_by_me: !post.liked_by_me, like_count: post.like_count + (post.liked_by_me ? -1 : 1) }) } catch (issue) { setError(issue.message) } finally { setBusy(false) } }
  async function removePost() { if (!window.confirm('Delete this check-in?')) return; setBusy(true); setError(''); try { await api.delete(`/posts/${post.id}`); onDelete(post.id) } catch (issue) { setError(issue.message) } finally { setBusy(false) } }
  const mine = post.is_mine
  return <article className={`rounded-2xl border p-5 shadow-sm ${mine ? 'border-[#BFE2C8] bg-[#F0F9F2]' : 'border-[#DDE9DF] bg-white'}`}><div className="flex gap-3"><AnonymousMark /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold text-[#234033]">{mine ? 'Your check-in' : 'Anonymous'}</p>{mine && <span className="mt-1 inline-block rounded-full bg-[#DDF2E4] px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-[#17633A]">Visible as yours only to you</span>}</div><time className="shrink-0 text-xs text-[#718277]">{date}</time></div><p className="mt-3 whitespace-pre-wrap text-[15px] leading-7 text-[#1F3428]">{post.content}</p>{(post.image_url_1 || post.image_url_2) && <div className={`mt-4 grid gap-2 ${post.image_url_2 ? 'grid-cols-2' : 'grid-cols-1'}`}>{[post.image_url_1, post.image_url_2].filter(Boolean).map((url) => <img key={url} src={url} alt="Post attachment" loading="lazy" className="aspect-square w-full rounded-xl border border-[#D6E5D9] object-cover" />)}</div>}<div className="mt-4 flex items-center gap-5 text-sm"><button disabled={busy} onClick={() => void toggleLike()} className={`inline-flex items-center gap-1.5 font-semibold ${post.liked_by_me ? 'text-[#C64E4E]' : 'text-[#627468]'}`}><Heart size={17} fill={post.liked_by_me ? 'currentColor' : 'none'} /> {post.like_count}</button><Link className="inline-flex items-center gap-1.5 font-semibold text-[#627468] hover:text-[#137B45]" to={`/post/${post.id}`}><MessageCircle size={17} /> {post.comment_count}</Link>{mine && <button disabled={busy} onClick={() => void removePost()} className="ml-auto text-xs font-bold text-[#A74545] underline">Delete</button>}</div>{error && <p role="alert" className="error mt-3">{error}</p>}</div></div></article>
}

function FeedSkeleton() { return <div className="space-y-4 py-5">{[1, 2, 3].map((key) => <div key={key} className="animate-pulse rounded-2xl border border-[#E1ECE3] bg-white p-5"><div className="h-4 w-24 rounded bg-[#E7F0E9]" /><div className="mt-4 h-3 w-full rounded bg-[#E7F0E9]" /><div className="mt-2 h-3 w-4/5 rounded bg-[#E7F0E9]" /></div>)}</div> }

export function Feed() {
  const [posts, setPosts] = useState([]); const [cursor, setCursor] = useState(null); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [error, setError] = useState(''); const [newAvailable, setNewAvailable] = useState(false); const sentinel = useRef(null)
  const load = useCallback(async (reset = false) => { if (loadingMore) return; if (reset && !posts.length) setLoading(true); if (!reset) setLoadingMore(true); setError(''); try { const activeCursor = reset ? null : cursor; const response = await api.get(`/feed?limit=12${activeCursor ? `&cursor=${encodeURIComponent(activeCursor)}` : ''}`); setPosts((current) => reset ? response.posts : [...current, ...response.posts]); setCursor(response.next_cursor); setNewAvailable(false) } catch (issue) { setError(issue.message) } finally { setLoading(false); setLoadingMore(false) } }, [cursor, loadingMore, posts.length])
  useEffect(() => { void load(true) }, [])
  useRealtimeEvent((event) => { if (event.type === 'post_created' || event.type === 'feed_changed') setNewAvailable(true) })
  useEffect(() => { const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting && cursor && !loadingMore) void load() }, { rootMargin: '300px' }); if (sentinel.current) observer.observe(sentinel.current); return () => observer.disconnect() }, [cursor, loadingMore, load])
  if (loading) return <FeedSkeleton />
  if (error && !posts.length) return <div className="py-10 text-sm text-[#A74545]">Could not load the feed. <button className="underline" onClick={() => void load(true)}>Try again</button></div>
  return <section className="relative mt-5"><div className="sticky top-16 z-10 flex justify-center">{newAvailable && <button onClick={() => void load(true)} className="inline-flex items-center gap-2 rounded-full bg-[#137B45] px-4 py-2 text-sm font-bold text-white shadow-lg"><RefreshCw size={15} /> New check-ins</button>}</div>{!posts.length ? <div className="py-12 text-center text-sm text-[#627468]">No check-ins yet. Be the first to share a study win.</div> : <div className="space-y-4">{posts.map((post) => <PostCard key={post.id} post={post} onChange={(next) => setPosts((current) => current.map((item) => item.id === next.id ? next : item))} onDelete={(id) => setPosts((current) => current.filter((post) => post.id !== id))} />)}</div>}{error && <p className="error mt-4">{error}</p>}<div ref={sentinel} className="py-6 text-center text-sm text-[#718277]">{loadingMore ? 'Loading more…' : cursor ? 'Keep scrolling for more' : posts.length ? 'You’re all caught up.' : ''}</div></section>
}
